# Generated by Django 4.0.5 on 2023-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='phone',
        ),
        migrations.AddField(
            model_name='retailer',
            name='phone_number',
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
